title: 그립 개발자 블로그
author:
  name: GitHub User
  email: your-email@domain.com
description: >
  Everyone can sell, 전국민 라이브 大장터

show_excerpts: true

minima:
  date_format: "%F"
  social_links:
    twitter: jekyllrb
    github:  jekyll

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
